(specifications->manifest
 '("glibc-locales"
   "shepherd"
   "guile"
   ;; hackeryarn
   "kanshi"
   "udiskie"
   "sway"
   "waybar"
   "fontconfig"
   "font-iosevka"
   "font-awesome"
   "dbus"
   "flatpak"
   "mit-scheme"
   "obs"
   "xdg-desktop-portal-wlr"
   "mu"
   "isync"))
